In [5]:
import pandas as pd
import numpy as np


nav = pd.read_csv(
"../data/processed/clean_nav_history.csv"
)


nav["date"] = pd.to_datetime(nav["date"])


nav.head()

   scheme_code       date     nav
0       119551 2026-06-20  105.25
1       119551 2026-06-21  106.00
2       119551 2026-06-22  106.80
3       119551 2026-06-23  107.40
4       119551 2026-06-24  108.10

In [6]:
nav["daily_return"] = (
    nav.groupby("scheme_code")
    ["nav"]
    .pct_change()
)


nav.head()

   scheme_code       date     nav  daily_return
0       119551 2026-06-20  105.25           NaN
1       119551 2026-06-21  106.00      0.007126
2       119551 2026-06-22  106.80      0.007547
3       119551 2026-06-23  107.40      0.005618
4       119551 2026-06-24  108.10      0.006518

In [7]:
VaR = (
    nav["daily_return"]
    .dropna()
    .quantile(0.05)
)


print("95% Value at Risk:", VaR)

95% Value at Risk: -0.017960391867617095

In [8]:
risk = (
    nav.groupby("scheme_code")
    ["daily_return"]
    .agg(
        volatility="std"
    )
)


risk.sort_values(
"volatility"
).head()

             volatility
scheme_code
140001         0.000986
130001         0.002204
125497         0.005956
119551         0.011641
120503         0.011757

In [9]:
score = pd.read_csv(
"../data/processed/fund_scorecard.csv"
)


score["recommendation_score"] = (
    score.select_dtypes("number")
    .mean(axis=1)
)


recommendation = score.sort_values(
"recommendation_score",
ascending=False
)


recommendation.head()

   scheme_code  expense_ratio  recommendation_score
2         1004            1.5                502.75
1         1002            0.8                501.40
0         1001            1.2                501.10

In [10]:
recommendation.to_csv(
"../data/processed/fund_recommendation.csv",
index=False
)

print("Recommendation file created")

Recommendation file created